export type PositionStatus = "unapplied" | "applied";
export type ApplicationStatus = "active" | "offer" | "rejected";
export type SortField = "priority" | "submitted_on";
export type SortOrder = "asc" | "desc";
export type StageType = string;
export type StageStatus = "scheduled" | "passed" | "failed";
export type DeletionTargetType = "company" | "campaign" | "position" | "application";
export type ResourceOwnerType = "company" | "campaign" | "position" | "application" | "stage";

export interface Company { id: string; name: string; industry: string; homepage: string; notes: string; createdAt: string; updatedAt: string; }
export interface CompanyInput { id?: string; name: string; industry: string; homepage: string; notes: string; }
export interface Campaign { id: string; companyId: string; name: string; opensOn?: string; closesOn?: string; sourceUrl: string; lastVerifiedOn?: string; processOverview: string; notes: string; }
export interface CampaignInput { id?: string; companyId: string; name: string; opensOn: string; closesOn: string; sourceUrl: string; lastVerifiedOn: string; processOverview: string; notes: string; }
export interface Position { id: string; campaignId: string; title: string; jobCode: string; department: string; location: string; track: string; sourceUrl: string; priority: number; notes: string; }
export interface PositionInput { id?: string; campaignId: string; title: string; jobCode: string; department: string; location: string; track: string; sourceUrl: string; priority: number; notes: string; }
export interface QuickCapturePositionInput { companyName: string; companyIndustry: string; companyHomepage: string; companyNotes: string; campaignName: string; campaignOpensOn: string; campaignClosesOn: string; campaignSourceUrl: string; campaignLastVerifiedOn: string; campaignProcessOverview: string; campaignNotes: string; title: string; jobCode: string; department: string; location: string; track: string; sourceUrl: string; priority: number; notes: string; }
export interface PositionAttachment { id: string; positionId: string; originalName: string; storedName: string; mimeType: string; sizeBytes: number; createdAt: string; }
export interface PositionSummary extends Position { companyName: string; campaignName: string; status: PositionStatus; applicationId: string; applicationStatus: ApplicationStatus | ""; submittedOn: string; currentStageName: string; currentStageType: StageType | ""; currentStageStatus: StageStatus | ""; stageCount: number; }
export interface PositionPage { items: PositionSummary[]; page: number; pageSize: number; total: number; }
export interface Application { id: string; positionId: string; status: ApplicationStatus; submittedOn?: string; channel: string; resumeId: string; resumeName: string; notes: string; }
export interface ApplicationInput { id?: string; positionId: string; submittedOn: string; channel: string; resumeId: string; resumeName: string; notes: string; }
export interface ApplicationResume { id: string; applicationId: string; originalName: string; storedName: string; mimeType: string; sizeBytes: number; createdAt: string; }
export interface Resume { id: string; name: string; originalName: string; storedName: string; mimeType: string; sizeBytes: number; contentHash: string; archived: boolean; usageCount: number; createdAt: string; updatedAt: string; }
export interface ResumeInput { id: string; name: string; archived: boolean; }
export interface ApplicationStage { id: string; applicationId: string; sortOrder: number; content: string; type: StageType; status: StageStatus; scheduledStart?: string; scheduledEnd?: string; resultAt?: string; sourceUrl: string; notes: string; links: ResourceLink[]; attachments: SupplementalAttachment[]; }
export interface ApplicationStageInput { id?: string; applicationId: string; sortOrder: number; content: string; type: StageType; status: StageStatus; scheduledStart: string; scheduledEnd: string; resultAt: string; sourceUrl: string; notes: string; }
export interface StageTypeDefinition { id: StageType; name: string; system: boolean; createdAt: string; updatedAt: string; }
export interface StageTypeInput { id?: StageType; name: string; }
export interface ResourceLink { id: string; ownerType: ResourceOwnerType; ownerId: string; name: string; url: string; sortOrder: number; createdAt: string; updatedAt: string; }
export interface ResourceLinkInput { id?: string; name: string; url: string; }
export interface SupplementalAttachment { id: string; ownerType: ResourceOwnerType; ownerId: string; originalName: string; storedName: string; mimeType: string; sizeBytes: number; createdAt: string; }
export interface CompanyDetail { company: Company; campaigns: Campaign[]; campaignCount: number; positionCount: number; applicationCount: number; links: ResourceLink[]; attachments: SupplementalAttachment[]; }
export interface CampaignDetail { campaign: Campaign; company: Company; positionCount: number; applicationCount: number; links: ResourceLink[]; attachments: SupplementalAttachment[]; }
export interface DirectoryStats { companyCount: number; campaignCount: number; positionCount: number; applicationCount: number; }
export interface PositionDetail { position: Position; status: PositionStatus; company: Company; campaign: Campaign; application: Application | null; resume: Resume | null; stages: ApplicationStage[]; attachments: PositionAttachment[]; links: ResourceLink[]; }
export interface ApplicationSummary extends Application { companyName: string; campaignName: string; positionTitle: string; positionPriority: number; currentStageName: string; currentStageType: StageType | ""; currentStageStatus: StageStatus | ""; stageCount: number; stages: ApplicationStage[]; }
export interface ApplicationPage { items: ApplicationSummary[]; page: number; pageSize: number; total: number; }
export interface ApplicationDetail { application: Application; position: Position; company: Company; campaign: Campaign; resume: Resume | null; stages: ApplicationStage[]; links: ResourceLink[]; attachments: SupplementalAttachment[]; }
export interface ScheduleFilter { from: string; to: string; }
export interface ScheduleItem { id: string; stageId: string; applicationId: string; positionId: string; companyName: string; campaignName: string; positionTitle: string; applicationStatus: ApplicationStatus; name: string; type: StageType; status: StageStatus; kind: "stage" | "result"; startsAt: string; endsAt?: string; isCompleted: boolean; isOverdue: boolean; isWaitingResult: boolean; }
export interface StageProgressStats { type: StageType; entered: number; passed: number; failed: number; }
export interface Dashboard { statusCounts: { status: PositionStatus; count: number }[]; totalApplications: number; activeApplications: number; offerApplications: number; rejectedApplications: number; resumeScreeningStats: StageProgressStats; writtenTestStats: StageProgressStats; assessmentStats: StageProgressStats; interviewedApplications: number; interviewStats: StageProgressStats[]; todoCount: number; }
export interface Health { databasePath: string; schemaVersion: number; safety: { mirrorDirectory: string; latestSnapshot: string; lastSyncedAt: string; lastError: string; }; }
export interface BackupRecord { id: string; createdAt: string; databaseSize: number; attachmentCount: number; attachmentSize: number; }
export interface CloudSyncStatus { state: "local_only" | "pending" | "syncing" | "synced" | "failed" | "conflict" | "pending_confirmation" | "update_required" | "compatibility_unavailable"; activity: "" | "checking" | "compatibility" | "syncing" | "downloading" | "uploading" | "deleting"; message: string; owner: string; primaryRepo: string; deviceName: string; lastSuccessAt: string; lastCheckedAt: string; pendingChanges: number; activeChanges: number; queuedChanges: number; conflictCount: number; canSync: boolean; progressDone: number; progressTotal: number; filesDone: number; filesTotal: number; retryAttempt: number; retryMax: number; retryError: string; retryAfter: number; minimumClientVersion: string; requiredCapabilities: string[]; }
export interface SyncDataSummary { companies: number; campaigns: number; positions: number; applications: number; stages: number; attachments: number; resumes: number; }
export interface GiteeConnectionPreview { account: string; primaryRepo: string; local: SyncDataSummary; cloud: SyncDataSummary; recommended: "upload" | "download" | "merge"; needsConfirm: boolean; }
export interface SyncConflict { id: string; objectType: string; objectId: string; localUpdatedAt: string; remoteUpdatedAt: string; localDescription: string; remoteDescription: string; }
export interface BackupCenter { dataDirectory: string; backupDirectory: string; mirrorDirectory: string; lastSyncedAt: string; archivesCount: number; backups: BackupRecord[]; cloudSync: CloudSyncStatus; }
export interface RestoreResult { restoredBackup: BackupRecord; safetyBackup: BackupRecord; }
export interface DeleteInput { entityType: DeletionTargetType; id: string; confirmationText: string; }
export interface DeletionPreview { entityType: DeletionTargetType; entityName: string; confirmationText: string; campaignCount: number; positionCount: number; applicationCount: number; stageCount: number; }
export interface AppUpdate { currentVersion: string; latestVersion: string; available: boolean; state: "idle" | "checking" | "available" | "downloading" | "downloaded" | "installing" | "failed"; releaseNotes: string; publishedAt: string; releaseUrl: string; assetName: string; assetSize: number; downloadedBytes: number; message: string; networkStatus: string; checkedAt: string; }

interface BackendApp {
  Dashboard(): Promise<Dashboard>; Health(): Promise<Health>; ListCompanies(): Promise<Company[]>; DirectoryStats(): Promise<DirectoryStats>; GetCompanyDetail(companyId: string): Promise<CompanyDetail>; SaveCompany(input: CompanyInput): Promise<Company>;
  ListCampaigns(companyId: string): Promise<Campaign[]>; GetCampaignDetail(campaignId: string): Promise<CampaignDetail>; SaveCampaign(input: CampaignInput): Promise<Campaign>;
  ListPositions(filter: { status: string; query: string; sortBy: SortField; sortOrder: SortOrder; page: number; pageSize: number }): Promise<PositionPage>; SavePosition(input: PositionInput): Promise<Position>; QuickCapturePosition(input: QuickCapturePositionInput): Promise<Position>;
  ListApplications(filter: { status: string; query: string; sortBy: SortField; sortOrder: SortOrder; stageType: string; stageStatus: string; resumeId: string; page: number; pageSize: number }): Promise<ApplicationPage>;
  GetPositionDetail(positionId: string): Promise<PositionDetail>; GetApplicationDetail(applicationId: string): Promise<ApplicationDetail>;
  AddPositionAttachments(positionId: string): Promise<PositionAttachment[]>; ListPositionAttachments(positionId: string): Promise<PositionAttachment[]>; PastePositionImage(positionId: string, originalName: string, dataUrl: string): Promise<PositionAttachment[]>; UploadPositionAttachment(positionId: string, originalName: string, dataUrl: string): Promise<PositionAttachment[]>; PositionAttachmentDataURL(id: string): Promise<string>; OpenPositionAttachment(id: string): Promise<void>; DeletePositionAttachment(id: string): Promise<void>;
  ListResourceLinks(ownerType: ResourceOwnerType, ownerId: string): Promise<ResourceLink[]>; SaveResourceLinks(ownerType: ResourceOwnerType, ownerId: string, links: ResourceLinkInput[]): Promise<ResourceLink[]>;
  ListSupplementalAttachments(ownerType: ResourceOwnerType, ownerId: string): Promise<SupplementalAttachment[]>; UploadSupplementalAttachment(ownerType: ResourceOwnerType, ownerId: string, originalName: string, dataUrl: string): Promise<SupplementalAttachment[]>; PasteSupplementalImage(ownerType: ResourceOwnerType, ownerId: string, originalName: string, dataUrl: string): Promise<SupplementalAttachment[]>; SupplementalAttachmentDataURL(id: string): Promise<string>; OpenSupplementalAttachment(id: string): Promise<void>; DeleteSupplementalAttachment(id: string): Promise<void>;
  UploadApplicationResume(applicationId: string, originalName: string, dataUrl: string): Promise<ApplicationResume>; OpenApplicationResume(applicationId: string): Promise<void>; DeleteApplicationResume(applicationId: string): Promise<void>;
  ListResumes(includeArchived: boolean): Promise<Resume[]>; UploadResume(name: string, originalName: string, dataUrl: string): Promise<Resume>; SaveResume(input: ResumeInput): Promise<Resume>; OpenResume(id: string): Promise<void>; DeleteResume(id: string): Promise<void>; SetApplicationResume(applicationId: string, resumeId: string): Promise<void>; ClearApplicationResume(applicationId: string): Promise<void>;
  PreviewDeletion(input: DeleteInput): Promise<DeletionPreview>; DeleteEntity(input: DeleteInput): Promise<void>;
  SaveApplication(input: ApplicationInput): Promise<Application>; ListApplicationStages(applicationId: string): Promise<ApplicationStage[]>;
  ListScheduleItems(filter: ScheduleFilter): Promise<ScheduleItem[]>;
  ListStageTypes(): Promise<StageTypeDefinition[]>; SaveStageType(input: StageTypeInput): Promise<StageTypeDefinition>; DeleteStageType(id: StageType): Promise<void>;
  SaveApplicationStage(input: ApplicationStageInput): Promise<ApplicationStage>; DeleteApplicationStage(stageId: string): Promise<void>; ReorderApplicationStages(applicationId: string, stageIds: string[]): Promise<ApplicationStage[]>;
  CreateBackup(): Promise<string>; BackupCenter(): Promise<BackupCenter>; RestoreBackup(id: string, confirmation: string): Promise<RestoreResult>; OpenBackupLocation(kind: string): Promise<void>;
  CloudSyncStatus(): Promise<CloudSyncStatus>; ConnectGitee(token: string): Promise<GiteeConnectionPreview>; PendingGiteeConnectionPreview(): Promise<GiteeConnectionPreview>; ConfirmGiteeConnection(mode: "upload" | "download" | "merge"): Promise<CloudSyncStatus>; SyncGiteeNow(): Promise<CloudSyncStatus>; DisconnectGitee(): Promise<void>; DeleteGiteeSyncRepositories(): Promise<string[]>; ListSyncConflicts(): Promise<SyncConflict[]>; ResolveSyncConflict(id: string, choice: "local" | "remote"): Promise<void>;
  AppUpdateStatus(): Promise<AppUpdate>; CheckForAppUpdate(): Promise<AppUpdate>; DownloadAppUpdate(): Promise<AppUpdate>; InstallDownloadedUpdate(): Promise<void>;
}

declare global { interface Window { go?: { main?: { App?: BackendApp } }; } }
function backend(): BackendApp { const app = window.go?.main?.App; if (!app) throw new Error("OfferAtlas 后端尚未连接，请通过 Wails 启动应用"); return app; }

export const api = {
  dashboard: () => backend().Dashboard(), health: () => backend().Health(), companies: () => backend().ListCompanies(), directoryStats: () => backend().DirectoryStats(), companyDetail: (id: string) => backend().GetCompanyDetail(id), saveCompany: (input: CompanyInput) => backend().SaveCompany(input),
  campaigns: (companyId = "") => backend().ListCampaigns(companyId), campaignDetail: (id: string) => backend().GetCampaignDetail(id), saveCampaign: (input: CampaignInput) => backend().SaveCampaign(input),
  positions: (status = "all", query = "", page = 1, pageSize = 50, sortBy: SortField = "priority", sortOrder: SortOrder = "desc") => backend().ListPositions({ status, query, sortBy, sortOrder, page, pageSize }), savePosition: (input: PositionInput) => backend().SavePosition(input), quickCapturePosition: (input: QuickCapturePositionInput) => backend().QuickCapturePosition(input),
  applications: (filter: { status?: string; query?: string; page?: number; pageSize?: number; sortBy?: SortField; sortOrder?: SortOrder; stageType?: string; stageStatus?: string; resumeId?: string } = {}) => backend().ListApplications({ status: filter.status || "all", query: filter.query || "", sortBy: filter.sortBy || "priority", sortOrder: filter.sortOrder || "desc", stageType: filter.stageType || "", stageStatus: filter.stageStatus || "", resumeId: filter.resumeId || "", page: filter.page || 1, pageSize: filter.pageSize || 50 }),
  positionDetail: (id: string) => backend().GetPositionDetail(id), applicationDetail: (id: string) => backend().GetApplicationDetail(id),
  addPositionAttachments: (id: string) => backend().AddPositionAttachments(id), positionAttachments: (id: string) => backend().ListPositionAttachments(id), pastePositionImage: (positionID: string, originalName: string, dataURL: string) => backend().PastePositionImage(positionID, originalName, dataURL), uploadPositionAttachment: (positionID: string, originalName: string, dataURL: string) => backend().UploadPositionAttachment(positionID, originalName, dataURL), positionAttachmentDataURL: (id: string) => backend().PositionAttachmentDataURL(id), openPositionAttachment: (id: string) => backend().OpenPositionAttachment(id), deletePositionAttachment: (id: string) => backend().DeletePositionAttachment(id),
  resourceLinks: (ownerType: ResourceOwnerType, ownerID: string) => backend().ListResourceLinks(ownerType, ownerID), saveResourceLinks: (ownerType: ResourceOwnerType, ownerID: string, links: ResourceLinkInput[]) => backend().SaveResourceLinks(ownerType, ownerID, links),
  supplementalAttachments: (ownerType: ResourceOwnerType, ownerID: string) => backend().ListSupplementalAttachments(ownerType, ownerID), uploadSupplementalAttachment: (ownerType: ResourceOwnerType, ownerID: string, originalName: string, dataURL: string) => backend().UploadSupplementalAttachment(ownerType, ownerID, originalName, dataURL), pasteSupplementalImage: (ownerType: ResourceOwnerType, ownerID: string, originalName: string, dataURL: string) => backend().PasteSupplementalImage(ownerType, ownerID, originalName, dataURL), supplementalAttachmentDataURL: (id: string) => backend().SupplementalAttachmentDataURL(id), openSupplementalAttachment: (id: string) => backend().OpenSupplementalAttachment(id), deleteSupplementalAttachment: (id: string) => backend().DeleteSupplementalAttachment(id),
  uploadApplicationResume: (applicationID: string, originalName: string, dataURL: string) => backend().UploadApplicationResume(applicationID, originalName, dataURL), openApplicationResume: (applicationID: string) => backend().OpenApplicationResume(applicationID), deleteApplicationResume: (applicationID: string) => backend().DeleteApplicationResume(applicationID),
  resumes: (includeArchived = true) => backend().ListResumes(includeArchived), uploadResume: (name: string, originalName: string, dataURL: string) => backend().UploadResume(name, originalName, dataURL), saveResume: (input: ResumeInput) => backend().SaveResume(input), openResume: (id: string) => backend().OpenResume(id), deleteResume: (id: string) => backend().DeleteResume(id), setApplicationResume: (applicationID: string, resumeID: string) => backend().SetApplicationResume(applicationID, resumeID), clearApplicationResume: (applicationID: string) => backend().ClearApplicationResume(applicationID),
  previewDeletion: (entityType: DeletionTargetType, id: string) => backend().PreviewDeletion({ entityType, id, confirmationText: "" }), deleteEntity: (input: DeleteInput) => backend().DeleteEntity(input),
  saveApplication: (input: ApplicationInput) => backend().SaveApplication(input), stages: (id: string) => backend().ListApplicationStages(id), saveStage: (input: ApplicationStageInput) => backend().SaveApplicationStage(input), deleteStage: (id: string) => backend().DeleteApplicationStage(id), reorderStages: (applicationId: string, ids: string[]) => backend().ReorderApplicationStages(applicationId, ids), schedule: (filter: ScheduleFilter) => backend().ListScheduleItems(filter),
  stageTypes: () => backend().ListStageTypes(), saveStageType: (input: StageTypeInput) => backend().SaveStageType(input), deleteStageType: (id: StageType) => backend().DeleteStageType(id),
  backup: () => backend().CreateBackup(), backupCenter: () => backend().BackupCenter(), restoreBackup: (id: string, confirmation: string) => backend().RestoreBackup(id, confirmation), openBackupLocation: (kind: "data" | "backups" | "mirror") => backend().OpenBackupLocation(kind),
  cloudSyncStatus: () => backend().CloudSyncStatus(), connectGitee: (token: string) => backend().ConnectGitee(token), pendingGiteeConnectionPreview: () => backend().PendingGiteeConnectionPreview(), confirmGiteeConnection: (mode: "upload" | "download" | "merge") => backend().ConfirmGiteeConnection(mode), syncGiteeNow: () => backend().SyncGiteeNow(), disconnectGitee: () => backend().DisconnectGitee(), deleteGiteeSyncRepositories: () => backend().DeleteGiteeSyncRepositories(), syncConflicts: () => backend().ListSyncConflicts(), resolveSyncConflict: (id: string, choice: "local" | "remote") => backend().ResolveSyncConflict(id, choice),
  appUpdateStatus: () => backend().AppUpdateStatus(), checkForAppUpdate: () => backend().CheckForAppUpdate(), downloadAppUpdate: () => backend().DownloadAppUpdate(), installDownloadedUpdate: () => backend().InstallDownloadedUpdate(),
};
